export const Menus = [
  {
    id: 1,
    name: 'Home',
    path: '/',
  },
  {
    id: 2,
    name: 'Explore',
    path: '/explore',
  },
  {
    id: 3,
    name: 'Contact Us',
    path: '/contact-us',
  },
];

export const SocialMediaList = [
  {
    id: 1,
    name: 'Youtube',
    icon: '/assets/images/youtube.png',
    url: '',
  },
  {
    id: 2,
    name: 'Linkedin',
    icon: '/assets/images/linkedin.png',
    url: '',
  },
  {
    id: 3,
    name: 'Twitter',
    icon: '/assets/images/twitter.png',
    url: '',
  },
  {
    id: 4,
    name: 'Facebook',
    icon: '/assets/images/facebook.png',
    url: '',
  },
];

export const Categories = [
  {
    id: '1',
    icon: 'heart',
    name: 'Cardiologist',
    userId: '1',
  },
  {
    id: '2',
    icon: 'tooth',
    name: 'Dentist',
    userId: '1',
  },
  {
    id: '3',
    icon: 'joint',
    name: 'Orthopaedics',
    userId: '1',
  },
  {
    id: '4',
    icon: 'neurology',
    name: 'Neurosurgeon',
    userId: '1',
  },
  {
    id: '5',
    icon: 'ear',
    name: 'ENT Specialist',
    userId: '1',
  },
  {
    id: '6',
    icon: 'eye',
    name: 'Eye Specialist',
    userId: '1',
  },
  {
    id: '7',
    icon: 'mental',
    name: 'Physiatrists',
    userId: '1',
  },
  {
    id: '8',
    icon: 'doctor',
    name: 'General Doctor',
    userId: '1',
  },
  {
    id: '9',
    icon: 'oncology',
    name: 'Oncologist',
    userId: '1',
  },
  {
    id: '10',
    icon: 'body',
    name: 'Dermatologists',
    userId: '1',
  },
  {
    id: '11',
    icon: 'pediatrics',
    name: 'Pediatrician',
    userId: '1',
  },
];

export const Physicians = [
  {
    id: '1',
    title: 'Dr.',
    image: '/assets/images/doctor-img-1.jpg',
    name: 'John Green',
    userId: '1',
    category: 'Cardiologist',
    yearsOfExperience: '19 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '2',
    title: 'Dr.',
    image: '/assets/images/doctor-img-2.jpg',
    name: 'Leila Cameron',
    userId: '1',
    category: 'Dentist',
    yearsOfExperience: '18 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '3',
    title: 'Dr.',
    image: '/assets/images/doctor-img-3.jpg',
    name: 'David Livingston',
    userId: '1',
    category: 'Orthopaedics',
    yearsOfExperience: '25 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '4',
    title: 'Dr.',
    image: '/assets/images/doctor-img-4.jpg',
    name: 'Evan Peter',
    userId: '1',
    category: 'Neurosurgeon',
    yearsOfExperience: '8 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '5',
    title: 'Dr.',
    image: '/assets/images/doctor-img-5.jpg',
    name: 'Jane Powell',
    userId: '1',
    category: 'ENT Specialist',
    yearsOfExperience: '30 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '6',
    title: 'Dr.',
    image: '/assets/images/doctor-img-6.jpg',
    name: 'Alex Ramirez',
    userId: '1',
    category: 'Eye Specialist',
    yearsOfExperience: '20 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '7',
    title: 'Dr.',
    image: '/assets/images/doctor-img-7.jpg',
    name: 'Jasmine Lee',
    userId: '1',
    category: 'Mental Disorders',
    yearsOfExperience: '12 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '8',
    title: 'Dr.',
    image: '/assets/images/doctor-img-10.jpg',
    name: 'Alyana Cruz',
    userId: '1',
    category: 'General Doctor',
    yearsOfExperience: '15 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '9',
    title: 'Dr.',
    image: '/assets/images/doctor-img-9.jpg',
    name: 'Hardik Sharma',
    userId: '1',
    category: 'Outpatient',
    yearsOfExperience: '13 Years',
    address: '14 street avenue, Accra',
  },
  {
    id: '10',
    title: 'Dr.',
    image: '/assets/images/doctor-img-8.jpg',
    name: 'Anissa Rabiu',
    userId: '1',
    category: 'Cardiologist',
    yearsOfExperience: '10 Years',
    address: '14 street avenue, Accra',
  },
];

export const Appointments = [
  {
    id: '1',
    patient: '1',
    status: 'pending',
    physician: {
      name: 'Dr. Jamal Kofi',
      image: '/assets/images/doctor-img-7.jpg',
      address: '14 street avenue, Accra',
    },
    note: 'Headache',
    reason: '',
    userId: '1',
    cancellationReason: '',
    date: Date.now(),
    time: '3:00 PM',
  },
  {
    id: '2',
    patient: '1',
    status: 'scheduled',
    physician: {
      name: 'Dr. Anissa Rabiu',
      image: '/assets/images/doctor-img-8.jpg',
      address: '14 street avenue, Accra',
    },
    note: 'Headache',
    reason: '',
    userId: '1',
    cancellationReason: '',
    date: Date.now(),
    time: '3:00 PM',
  },
  {
    id: '3',
    patient: '1',
    status: 'cancelled',
    physician: {
      name: 'Dr. Hardik Sharma',
      image: '/assets/images/doctor-img-6.jpg',
      address: '14 street avenue, Accra',
    },
    note: 'Headache',
    reason: '',
    userId: '1',
    cancellationReason: '',
    date: '2024-09-30',
    time: '3:00 PM',
  },
];
